# Expression generated by update.sh; do not edit it by hand!
{
  stdenv,
  callPackage,
  ...
} @ args: let
  pname = "browseros";
  version = "0.30.0";

  allArchives = {
    aarch64-linux = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v${version}/BrowserOS_v${version}_arm64.dmg";
      hash = "sha256-/XLumOhKG7j8cuJxJgo7rj3p7ZuX2s3noVFldERijaE=";
    };
    x86_64-linux = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v${version}/BrowserOS_v${version}_amd64.deb";
      hash = "sha256-35Zpz82UXC7aF9g+LOE8Rmz0yZHT+ym044ND11qQH8g=";
    };
    aarch64-darwin = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v${version}/BrowserOS_v${version}_arm64.dmg";
      hash = "sha256-/XLumOhKG7j8cuJxJgo7rj3p7ZuX2s3noVFldERijaE=";
    };
    x86_64-darwin = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v${version}/BrowserOS_v${version}_x64.dmg";
      hash = "sha256-GziL9YxrqKt8LJ3oxQJO8ItADyL/qZFDJI/po9GYFCM=";
    };
  };

  archive =
    if builtins.hasAttr stdenv.system allArchives
    then allArchives.${stdenv.system}
    else throw "Unsupported platform.";
in
  callPackage ./browseros.nix (removeAttrs args ["callPackage"]) (
    archive
    // {
      inherit pname version;
    }
  )
