# Expression generated by update.sh; do not edit it by hand!
{
  stdenv,
  callPackage,
  ...
} @ args: let
  pname = "browseros";
  version = "0.28.0";

  allArchives = {
    aarch64-linux = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v${version}/BrowserOS_v${version}_arm64.dmg";
      hash = "sha256-KYy7EPbxLiOY9zsU/kFRXAqdTi4Mm0nkBW9uGqQjCv0=";
    };
    x86_64-linux = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v${version}/BrowserOS_v${version}_amd64.deb";
      hash = "sha256-6PFL3UspHtjhc1C4rLOoO/pZmApxBUDTvjqI+XzPPNg=";
    };
    aarch64-darwin = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v${version}/BrowserOS_v${version}_arm64.dmg";
      hash = "sha256-KYy7EPbxLiOY9zsU/kFRXAqdTi4Mm0nkBW9uGqQjCv0=";
    };
    x86_64-darwin = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v${version}/BrowserOS_v${version}_x64.dmg";
      hash = "sha256-8h7OsZlB30uqIE2Ma4gE2bwxzke3vA4+sUP7gTKelw8=";
    };
  };

  archive =
    if builtins.hasAttr stdenv.system allArchives
    then allArchives.${stdenv.system}
    else throw "Unsupported platform.";
in
  callPackage ./browseros.nix (removeAttrs args ["callPackage"]) (
    archive
    // {
      inherit pname version;
    }
  )
