#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl gnused nix jq

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

latestVersion="$(curl --fail -s ${GITHUB_TOKEN:+-u ":$GITHUB_TOKEN"} "https://api.github.com/repos/browseros-ai/BrowserOS/releases/latest" | jq -r '.tag_name' | sed 's/^v//')"

hashAarch64="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/browseros-ai/BrowserOS/releases/download/v${latestVersion}/BrowserOS_v${latestVersion}_arm64.dmg")")"
hashAmd64="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/browseros-ai/BrowserOS/releases/download/v${latestVersion}/BrowserOS_v${latestVersion}_amd64.deb")")"
hashAarch64Darwin="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/browseros-ai/BrowserOS/releases/download/v${latestVersion}/BrowserOS_v${latestVersion}_arm64.dmg")")"
hashAmd64Darwin="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/browseros-ai/BrowserOS/releases/download/v${latestVersion}/BrowserOS_v${latestVersion}_x64.dmg")")"

cat > $SCRIPT_DIR/package.nix << EOF
# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

let
  pname = "browseros";
  version = "${latestVersion}";

  allArchives = {
    aarch64-linux = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v\${version}/BrowserOS_v\${version}_arm64.dmg";
      hash = "${hashAarch64}";
    };
    x86_64-linux = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v\${version}/BrowserOS_v\${version}_amd64.deb";
      hash = "${hashAmd64}";
    };
    aarch64-darwin = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v\${version}/BrowserOS_v\${version}_arm64.dmg";
      hash = "${hashAarch64Darwin}";
    };
    x86_64-darwin = {
      url = "https://github.com/browseros-ai/BrowserOS/releases/download/v\${version}/BrowserOS_v\${version}_x64.dmg";
      hash = "${hashAmd64Darwin}";
    };
  };

  archive =
    if builtins.hasAttr stdenv.system allArchives then
      allArchives.\${stdenv.system}
    else
      throw "Unsupported platform.";

in
callPackage ./browseros.nix (removeAttrs args [ "callPackage" ]) (
  archive
  // {
    inherit pname version;
  }
)
EOF
